#!/bin/bash
# Script to convert a single VA InstandId to Instance Name

# Take standard input
instanceId=$1

# AWS describe-instance with query option to traverse the JSON and grep to display converted name
aws ec2 describe-instances --instance-ids "$instanceId" --query 'Reservations[0].Instances[*].Tags[?Key==`Name`]' --profile OR_json | grep -oP "[a-z0-9]+\-[a-z0-9]+\-[a-z0-9]+\-[a-z0-9\-]+"




